### ISSUE TITLE
Missing builtins module for RHEL/CentOS/SL (concreate 1.3.0)

### ISSUE THREAD

**Issue by pszubiak** [concrt/concreate#138]
I hit following problem during osbs engine build on Scientific Linux 7.3 x86_64:

concreate build --build-engine=osbs
2017-11-24 19:15:12,754 concreate    INFO     Initializing image descriptor...
2017-11-24 19:15:18,966 concreate    INFO     Handling modules...
2017-11-24 19:15:18,975 concreate    INFO     Handling additional repository files...
2017-11-24 19:15:20,056 concreate    INFO     Handling additional repository files...
2017-11-24 19:15:20,671 concreate    INFO     Handling artifacts...
2017-11-24 19:15:21,756 concreate    INFO     Rendering Dockerfile...
Traceback (most recent call last):
  File "/usr/bin/concreate", line 9, in <module>
    load_entry_point('concreate==1.3.0', 'console_scripts', 'concreate')()
  File "/usr/lib/python2.7/site-packages/concreate/cli.py", line 187, in run
    Concreate().parse().run()
  File "/usr/lib/python2.7/site-packages/concreate/cli.py", line 154, in run
    builder = Builder(self.args.build_engine, self.args.target)
  File "/usr/lib/python2.7/site-packages/concreate/builder.py", line 23, in __new__
    from concreate.builders.osbs import OSBSBuilder as BuilderImpl
  File "/usr/lib/python2.7/site-packages/concreate/builders/osbs.py", line 7, in <module>
    from builtins import input
ImportError: No module named builtins

It seems that this issue could be resolved by installing future package for python 2.7.

**Comment by dbecvarik** [comment]
maybe related to #139, @goldmann  can you take  a look?

**Comment by goldmann** [comment]
Merged, thanks!
