### ISSUE TITLE
Traceback when descriptor is missing name key

### ISSUE THREAD

**Issue by goldmann** [concrt/concreate#155]
Instead, I should get a validation error.

```
2017-12-07 15:25:58,315 concreate    DEBUG    Running version 1.3.3
2017-12-07 15:25:58,316 concreate    DEBUG    Loading descriptor from path 'image.yaml'.
2017-12-07 15:25:58,320 concreate    INFO     Initializing image descriptor...
Traceback (most recent call last):
  File "/usr/bin/concreate", line 11, in <module>
    load_entry_point('concreate==1.3.3', 'console_scripts', 'concreate')()
  File "/usr/lib/python3.6/site-packages/concreate/cli.py", line 187, in run
    Concreate().parse().run()
  File "/usr/lib/python3.6/site-packages/concreate/cli.py", line 133, in run
    os.path.join(self.args.target, 'repo'))
  File "/usr/lib/python3.6/site-packages/concreate/module.py", line 67, in get_dependencies
    logger.debug("Retrieving module repositories for '%s'" % (descriptor['name']))
  File "/usr/lib/python3.6/site-packages/concreate/descriptor.py", line 91, in __getitem__
    return self.descriptor[key]
KeyError: 'name'
```

**Comment by dbecvarik** [comment]
fixed by #179
